cf_1_connectios: [2, 3, 4] # recieved information from 
cf_2_connectios: [1, 3, 4]
cf_3_connectios: [1, 2, 4]
cf_4_connectios: [3, 2, 3]
cf_5_connectios: []
cf_6_connectios: []
cf_7_connectios: []
cf_8_connectios: []
cf_9_connectios: []
cf_10_connectios: []